### PR TITLE
Issue #470 - Revert action doesn't work on Definitions List

### LINKED ISSUE #470: Revert action doesn't work on Definitions list
Once updated the value of any field of a component in the Definitions list, the Revert button of the specific field doesn't restore the original value.

### PR DESCRIPTION
**Pull request by storrisi**
Fixes #470

### CODE REVIEW

File: src/components/LicensesRenderer.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ class LicensesRenderer extends Component {
     const { advancedView } = this.state
 
     return (
-      <div class="license-renderer">
+      <div className="license-renderer">
```
Comment (dabutvin) [inline src/components/LicensesRenderer.js]: 👍
