### PR TITLE
Fix buttons on /curation and the 'Collapse All' in /definitions pages

### LINKED ISSUE #531: Fix buttons on /curation and the 'Collapse All' in /definitions
We noticed that the buttons at the top on a /curation (e.g [link](https://dev.clearlydefined.io/curations/185)) "Done" and "Collapse All" are always disabled and don't do anything.

- Should we remove the "Done" button? I believe it's not possible to make any changes in this page currently.
- Should we fix the "Collapse All" button and make sure it also expands all the components when clicked back? (the same for [/definitions](https://dev.clearlydefined.io/definitions) page)

### PR DESCRIPTION
**Pull request by storrisi**
Fixes #531

### CODE REVIEW

File: src/components/SystemManagedList.js [hunk 1]
```diff
@@ -336,5 +344,5 @@ export default class SystemManagedList extends Component {
     this.getCurations(curationsToGet)
   }
 
-  updateList() {}
+  updateList(_) {}
```
Comment (storrisi) [inline src/components/SystemManagedList.js]: I'm not so sure about this change, what the `_` is supposed to do?

File: src/components/Navigation/Pages/PageBrowse/ButtonsBar.js [hunk 2]
```diff
@@ -20,8 +21,8 @@ export default class ButtonsBar extends Component {
             <span>&nbsp;Revert Changes</span>
           </Button>
         </ButtonWithTooltip>
-        <Button bsStyle="default" disabled={hasChanges} onClick={collapseAll}>
-          Collapse All
+        <Button bsStyle="default" onClick={toggleCollapseExpandAll}>
+          Toggle Collapse
```
Comment (storrisi) [inline src/components/Navigation/Pages/PageBrowse/ButtonsBar.js]: Should we really need an "expand all" method to expand all the shown definitions in the list? I'm not so sure about this.
@jeffmcaffer what do you think?

File: src/components/SystemManagedList.js (hunk 1 above)
Comment (gianpaj) [reply src/components/SystemManagedList.js]: This fixes a linting issue saying that the `updateList()` function doesn't require any arguments because this function is called with one argument. See line `339` for example.

If I remove the `_` variable argument, I get this:
SystemManagedList_js_—_website

File: src/components/Navigation/Pages/PageBrowse/ButtonsBar.js (hunk 2 above)
Comment (gianpaj) [reply src/components/Navigation/Pages/PageBrowse/ButtonsBar.js]: Maybe I misinterpreted @jeffmcaffer's [comment](https://github.com/clearlydefined/website/issues/531#issuecomment-468717062). Happy to make it only collapse though I think the button should expand the components if you can collapse them

**Comment by gianpaj** [comment]
I believe they're failing intermittently in the CI, as they pass locally:
The e2e tests that are failing are about the Home page.
```
TEST_HOST=http://localhost:3000 npm run e2e:test -t 'home'

> website@0.1.0 e2e:test /Users/gianfranco/clearlydefined/website
> jest -c e2e/jest.config.js "home"

 PASS  e2e/tests/home.js
  Home page
    ✓ should display "ClearlyDefined" text on page (267ms)
    Home page sections
      ✓ should have a "ClearlyDescribed" section (12ms)
      ✓ should have a "ClearlyLicensed" section (28ms)
      ✓ should have a "ClearlySecure" section (5ms)

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        2.668s, estimated 9s
```

**Comment by gianpaj** [comment]
FYI this is how the collapse/expand button now behaves:

collapse-issue-512

**Comment by storrisi** [comment]
@jeffmcaffer do you have any feedback on the behavior implemented here?

**Comment by storrisi** [comment]
@dabutvin do you think we can merge this one?

**Comment by jeffmcaffer** [comment]
Is this good to go?

**Comment by dabutvin** [comment]
👍
