### PR TITLE
Added sort by lowest Score after a "Fix something" selection

### LINKED ISSUE #593: Add sort after Browse page "Fix something" selection
Once a user has made a "Fix something" selection from the dropdown we should then sort to display lowest-scored components first.

### PR DESCRIPTION
**Pull request by storrisi**
Fixes #593

### CODE REVIEW

File: src/components/Navigation/Pages/PageBrowse/PageBrowse.js [hunk 1]
```diff
@@ -126,13 +126,22 @@ class PageBrowse extends SystemManagedList {
...
+    let activeSort = null
     if (overwrite !== true) {
       const filterValue = get(activeFilters, filter.type)
       if (filterValue && activeFilters[filter.type] === filter.value) delete activeFilters[filter.type]
       else activeFilters[filter.type] = filter.value
     }
-    this.setState({ ...this.state, activeFilters: Object.keys(activeFilters).length > 0 ? activeFilters : null }, () =>
-      this.updateData()
+    if (filter.type === 'curate') {
+      activeSort = 'effectiveScore'
```
Comment (dabutvin) [inline src/components/Navigation/Pages/PageBrowse/PageBrowse.js]: Could we get the checkmark to display in the sort dropdown when this happens?

**Comment by storrisi** [comment]
Thanks @dabutvin , i've now used the property 'score' which is bound to the Dropdown menu
