### PR TITLE
Fixed FullDetails commit string if sourceLocation is not available

### LINKED ISSUE #254: "Dig In" to `async-limiter` package shows white screen
See the GIF. The other packages I tried show the modal appropriately.
It's something specific to `async-limiter`

### PR DESCRIPTION
**Pull request by storrisi**
* fixes #254

### CODE REVIEW

File: src/components/FullDetailView/FullDetailPage.js [hunk 1]
```diff
@@ -98,8 +98,13 @@ export class FullDetailPage extends Component {
...
     const { changes } = this.state
-    if (!component && !nextComponent) return false
-
+    if (
+      (!component || isEmpty(component.changes)) &&
+      (!nextComponent || isEmpty(nextComponent.changes)) &&
+      isEmpty(changes)
+    )
+      return false
+    console.log(component, nextComponent, changes)
```
Comment (dabutvin) [inline src/components/FullDetailView/FullDetailPage.js]: do we need to keep the `console.log` statement?

Comment (storrisi) [reply src/components/FullDetailView/FullDetailPage.js]: Of course we don't. Just updated the PR removing this instruction.
